### ISSUE TITLE
Feature Request: Persist default clone location for new repo clone, and not a static one

### ISSUE THREAD

**Issue by Viranchee** [punitda/ssh-git#51]
Current default static clone location: /Users/<UserName>/Desktop

After feature gets implemented:
I select folder F to clone Repo R1
For cloning another repo R2, The app persists folder F's location and auto fills it in the Clone directory folder

a repeated step gets out of the way, for cloning multiple repositories

**Comment by punitda** [comment]
@Viranchee  I think it does what you are asking already. I agree due to button state showing "Clone Successfully" and not reverting back to "Clone Repo" state after successful clone (UI problem) it doesn't look obvious that after cloning one repo you can clone another one without closing "Clone Repo" dialog so the folder location stays same as selected earlier.

Based on this idea, I'll add the same setting in user preferences too so that user could select default clone location like browsers do for download location. 
Thanks for filing the issue 👍

**Comment by punitda** [comment]
With new UI introduced in v0.0.3 for cloning repo and updating remote url this is no longer applicable. So, closing this issue.
